### ISSUE TITLE
Login no longer working

### ISSUE THREAD

**Issue by AlexandruCapatina94** [outkastm/Filelist.ro#13]
Hello,

First of all, thanks for the awesome plugin.

As of recently, the login no longer works. I get the following error in couchpotato:

[hpotato.core.plugins.base] Failed opening url in Filelist: https://filelist.ro/api.php?username=xxx&category=26&passkey=xxx&action=search-torrents&query=tt6806448&type=imdb Traceback (most recent call last): HTTPError: 403 Client Error: Forbidden for url: https://filelist.ro/api.php?username=xxx&category=26&passkey=xxx&action=search-torrents&query=tt6806448&type=imdb

**Comment by cosmincc** [comment]
The passkey to use the API is not the login password. You can find it in your profile: https://filelist.io/my.php

**Comment by AlexandruCapatina94** [comment]
Thanks. It seems I had an earlier version of the main.py and it didn't have the passkey implemented. Downloaded the latest version and it works.

Rookie mistake.
