### ISSUE TITLE
Filelist does not appear in search providers

### ISSUE THREAD

**Issue by simistef** [outkastm/Filelist.ro#6]
Hi there,

I have couchpotato version:

Version 5b1dd686 (17 Jan 2015 14:04:58 EET)
Updater git, masterID12701
Directories
/usr/local/couchpotatoserver/share/CouchPotatoServer
/usr/local/couchpotatoserver/var
Startup Args
['--daemon', '--pid_file', '/usr/local/couchpotatoserver/var/couchpotatoserver.pid', '--config_file', '/usr/local/couchpotatoserver/var/settings.conf']Namespace(config_file='/usr/local/couchpotatoserver/var/settings.conf', console_log=False, daemon=True, data_dir=None, debug=False, pid_file='/usr/local/couchpotatoserver/var/couchpotatoserver.pid', quiet=False)

I have copied the files inside the folder /usr/local/couchpotatoserver/var/filelist but it does not appear on the torrent provider list. The logs are empty and do not show any errors ?

Any idea what i can do to make this work ?

Thanks,
Simion

**Comment by outkastm** [comment]
place the filelist folder inside /usr/local/couchpotatoserver/var/filelist/custom_plugins and restart CPS

**Comment by simistef** [comment]
thanks for your answer. 

i have put the files in folder: /usr/local/couchpotatoserver/var/custom_plugins/filelist restarted CP and server, but still nothing.

here is a screenshot of path and files: http://i.imgur.com/YW9fZM1.png?1

**Comment by outkastm** [comment]
inside folder custom_plugins create a folder filelist and place the 2 files there

**Comment by simistef** [comment]
Yes, this is what I did. Please see the screenshot link from my previous message.

**Comment by outkastm** [comment]
custom_plugins folder was there or you create that folder ?

**Comment by simistef** [comment]
Yes, it was there already. I am using CouchPotato for Synology NAS with DSM 5.1.
But it did work for me in the past. Not sure if this might be the problem.

**Comment by simistef** [comment]
I have managed to install other custom plugin's fine, but only this is not working. Any idea where i could maybe see some logs on this ?

**Comment by ovidiub13** [comment]
Still experiencing this with CP
Version    e6fa8b8b (04.10.2015, 12:13:08)
Updater    git, master
ID    60 (54)
Directories    /app/couchpotato
    /config/data
Startup Args    ['--config_file=/config/config.ini', '--data_dir=/config/data']
    Namespace(config_file='/config/config.ini', console_log=False, daemon=False, data_dir='/config/data', debug=False, pid_file='/config/data/couchpotato.pid', quiet=False)

I see no logs related to this.

**Comment by donnib** [comment]
@ovidiub13 @outkastm did you solve the problem ? I have this problem too.

**Comment by ovidiub13** [comment]
I have no idea what's the status of this currently. I haven't used it for a very long time... If I'll look in the future and it still doesn't work, I'll come back here.

**Comment by donnib** [comment]
@ovidiub13 Merci ;)

**Comment by donnib** [comment]
@outkastm do you use this plugin with your own instance ? If so what CPS version do you run ?

**Comment by outkastm** [comment]
I use the latest CP 3.01 updated to latest GIT version

**Comment by ovidiub13** [comment]
I've just tested this in:
```
Version    4a0999d9 (06.09.2016, 12:53:22)
Updater    git, master
ID    224 (220)
Directories    /app/couchpotato
    /config/data
Startup Args    ['--config_file=/config/config.ini', '--data_dir=/config/data']
    Namespace(config_file='/config/config.ini', console_log=False, daemon=False, data_dir='/config/data', debug=False, pid_file='/config/data/couchpotato.pid', quiet=False)
```

And if you set it up as instructed in the readme it works as expected. Please close this issue.
